In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [2]:
### load the trained model , scaler pickle , onehot

model = load_model('model.h5')

### load the encoder and scalar
with open('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo = pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
### Example input data

input_data = {
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [8]:
# One-hot encode 'Geography'
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\Samiksha\OneDrive\Desktop\Python-genAi\ANNProjectImplementation\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [9]:
input_df = pd.DataFrame([input_data])
input_df

   CreditScore Geography  ...  IsActiveMember  EstimatedSalary
0          600    France  ...               1            50000

[1 rows x 10 columns]

In [10]:
## Encode categorical variable

input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

   CreditScore Geography  ...  IsActiveMember  EstimatedSalary
0          600    France  ...               1            50000

[1 rows x 10 columns]

In [11]:
### Concatination of onehot encoded data

input_df = pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df] , axis=1)
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [12]:
### Scaling the input data

input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [13]:
### predict churn 

prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step

array([[0.03995323]], dtype=float32)

In [15]:
prediction_probability = prediction[0][0]

if prediction_probability>0.5:
    print("Customer is likely to churn.")
else:
    print("Customer is not likely to churn.")

Customer is not likely to churn.